"use client";

import { useEffect, useState } from 'react';

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000/api';
type RequestItem = { _id: string; type: string; subject: string; description: string; status: string; response?: string };
type Notice = { _id: string; title: string; message: string; readAt?: string };

async function api(path: string, options: RequestInit = {}) { const response = await fetch(`${API_BASE}${path}`, { ...options, credentials: 'include', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('portal_token') || ''}`, ...(options.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Request failed'); return data; }

export default function SupportPage() {
  const [requests, setRequests] = useState<RequestItem[]>([]); const [notifications, setNotifications] = useState<Notice[]>([]); const [form, setForm] = useState({ type: 'academic', subject: '', description: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { Promise.all([api('/v1/requests'), api('/v1/notifications')]).then(([requestData, notificationData]) => { setRequests(requestData.requests || []); setNotifications(notificationData.notifications || []); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Unable to load support data')); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); try { const data = await api('/v1/requests', { method: 'POST', body: JSON.stringify(form) }); setRequests((items) => [data.request, ...items]); setForm({ type: 'academic', subject: '', description: '' }); setMessage('Request submitted successfully.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to submit request'); } }
  return <div className="space-y-6"><section className="rounded-[28px] bg-[#f8fafc] p-6 ring-1 ring-slate-200"><p className="muted-kicker">Student services</p><h2 className="mt-2 text-2xl font-bold text-[#11222d]">Requests and notifications</h2><form onSubmit={submit} className="mt-5 grid gap-3"><div className="grid gap-3 sm:grid-cols-2"><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} className="input-field"><option value="academic">Academic</option><option value="finance">Finance</option><option value="technical">Technical</option><option value="general">General</option></select><input required value={form.subject} onChange={(event) => setForm({ ...form, subject: event.target.value })} placeholder="Subject" className="input-field" /></div><textarea required value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Describe your request" className="input-field min-h-28" /><button className="w-fit rounded-lg bg-[#0d5a4d] px-4 py-2 text-sm font-semibold text-white">Submit request</button></form>{message && <p className="mt-3 text-sm text-green-700">{message}</p>}{error && <p className="mt-3 text-sm text-red-700">{error}</p>}</section><section className="rounded-[28px] bg-[#f8fafc] p-6 ring-1 ring-slate-200"><h3 className="text-xl font-bold text-[#11222d]">My requests</h3><div className="mt-4 space-y-3">{requests.length ? requests.map((item) => <div key={item._id} className="rounded-xl bg-white p-4 ring-1 ring-slate-200"><div className="flex justify-between gap-3"><strong>{item.subject}</strong><span className="text-sm capitalize text-[#0d5a4d]">{item.status.replace('_', ' ')}</span></div><p className="mt-2 text-sm text-slate-600">{item.description}</p>{item.response && <p className="mt-2 border-t pt-2 text-sm text-slate-700"><strong>Response:</strong> {item.response}</p>}</div>) : <p className="text-sm text-slate-500">No requests yet.</p>}</div></section><section className="rounded-[28px] bg-[#f8fafc] p-6 ring-1 ring-slate-200"><h3 className="text-xl font-bold text-[#11222d]">Notifications</h3><div className="mt-4 space-y-3">{notifications.length ? notifications.map((item) => <div key={item._id} className="rounded-xl bg-white p-4 ring-1 ring-slate-200"><strong>{item.title}</strong><p className="mt-1 text-sm text-slate-600">{item.message}</p></div>) : <p className="text-sm text-slate-500">No notifications.</p>}</div></section></div>;
}
