"use client";

import { useEffect, useState } from "react";
import { API_BASE } from "@/lib/config";

type RequestItem = { _id: string; type: string; subject: string; description: string; status: string; response?: string };
type Notice = { _id: string; title: string; message: string; readAt?: string };
async function api(path: string, options: RequestInit = {}) { const response = await fetch(`${API_BASE}${path}`, { ...options, credentials: "include", headers: { "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("portal_token") || ""}`, ...(options.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Request failed"); return data; }

export default function SupportPage() {
  const [requests, setRequests] = useState<RequestItem[]>([]); const [notifications, setNotifications] = useState<Notice[]>([]); const [form, setForm] = useState({ type: "academic", subject: "", description: "" }); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api("/v1/requests"), api("/v1/notifications")]).then(([requestData, notificationData]) => { setRequests(requestData.requests || []); setNotifications(notificationData.notifications || []); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load support data")); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); try { const data = await api("/v1/requests", { method: "POST", body: JSON.stringify(form) }); setRequests((items) => [data.request, ...items]); setForm({ type: "academic", subject: "", description: "" }); setMessage("Request submitted successfully."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to submit request"); } }

  return <div className="pg-page">
    <section className="pg-card"><div className="pg-page-head"><p className="pg-eyebrow">Student services</p><h1 className="pg-page-title">Requests and support</h1><p className="pg-page-subtitle">Send a request to the appropriate campus support team.</p></div><form onSubmit={submit} className="pg-form-section support-form"><label className="pg-label">Request category<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} className="pg-select"><option value="academic">Academic</option><option value="finance">Finance</option><option value="technical">Technical</option><option value="general">General</option></select></label><label className="pg-label">Subject<input required value={form.subject} onChange={(event) => setForm({ ...form, subject: event.target.value })} className="pg-input" /></label><label className="pg-label support-message">Message<textarea required value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className="pg-textarea" /></label><div className="profile-form-actions"><button className="pg-btn pg-btn-primary">Submit request</button>{message && <span className="pg-feedback success">{message}</span>}{error && <span className="pg-feedback error">{error}</span>}</div></form></section>
    <section className="pg-card"><div className="pg-page-head"><h2 className="pg-page-title">My requests</h2></div><div className="support-list">{requests.length ? requests.map((item) => <article key={item._id} className="req-card"><div className="req-card-head"><div><h3 className="req-card-title">{item.subject}</h3><span className="req-card-meta">{item.type}</span></div><span className="pg-badge pg-badge-crimson">{item.status.replace("_", " ")}</span></div><p className="req-card-body">{item.description}</p>{item.response && <p className="req-response"><strong>Response:</strong> {item.response}</p>}</article>) : <div className="pg-empty"><p>No requests yet.</p></div>}</div></section>
    <section className="pg-card"><div className="pg-page-head"><h2 className="pg-page-title">Notifications</h2></div><div className="support-list">{notifications.length ? notifications.map((item) => <article key={item._id} className="pg-row"><div><strong className="pg-row-title">{item.title}</strong><p className="pg-row-sub">{item.message}</p></div><span className={`pg-badge ${item.readAt ? "pg-badge-slate" : "pg-badge-gold"}`}>{item.readAt ? "Read" : "New"}</span></article>) : <div className="pg-empty"><p>No notifications.</p></div>}</div></section>
  </div>;
}
