"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, CalendarDays, ChevronRight, CircleDollarSign, Clock3, FileText, GraduationCap, MapPin, PlayCircle, Plus, ReceiptText } from "lucide-react";
import { fetchStudentOverview, type StudentOverview } from "@/lib/portal";

const courseFallback = [
  { code: "CS 301", title: "Database Systems", professor: "Dr. A. Mensah", grade: 86, progress: 72, tone: "indigo" },
  { code: "CS 315", title: "Software Engineering", professor: "Prof. E. Owusu", grade: 91, progress: 66, tone: "emerald" },
  { code: "MATH 241", title: "Discrete Mathematics", professor: "Dr. N. Asante", grade: 78, progress: 58, tone: "amber" },
];

export default function StudentDashboardPage() {
  const [overview, setOverview] = useState<StudentOverview | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { fetchStudentOverview().then(setOverview).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load dashboard")).finally(() => setLoading(false)); }, []);
  const profile = overview?.profile;
  const resultCourses = overview?.results?.slice(0, 3).map((row, index) => ({ code: row.courseId?.code || courseFallback[index].code, title: row.courseId?.title || courseFallback[index].title, professor: courseFallback[index].professor, grade: row.score || courseFallback[index].grade, progress: courseFallback[index].progress, tone: courseFallback[index].tone })) || courseFallback;
  const name = profile?.fullName?.split(" ")[0] || "Alex";

  return <div className="student-home">
    <section className="home-heading"><div><p className="eyebrow">Thursday, October 1</p><h1>Good morning, {name} <span>✦</span></h1><p>Here&apos;s what&apos;s happening with your studies today.</p></div><div className="quick-actions"><Link href="/dashboard/student/transcript"><FileText size={17} />Request transcript</Link><Link className="primary-action" href="/dashboard/student/fees"><CircleDollarSign size={17} />Pay balance</Link></div></section>
    {error && <div className="inline-notice" role="status">We couldn&apos;t refresh your latest data. Showing your workspace essentials.</div>}
    <section className="schedule-card"><div className="schedule-label"><span><CalendarDays size={18} />Today&apos;s schedule</span><Link href="/dashboard/student/timetable">Full timetable <ArrowRight size={16} /></Link></div><div className="schedule-items"><article className="schedule-class current"><div className="time"><strong>09:00</strong><span>10:30 AM</span></div><div className="class-marker"><i /><span /></div><div className="class-info"><div><b>Database Systems</b><span>CS 301 · Lecture</span></div><p><MapPin size={14} /> Science Block, Room 2.14</p></div><div className="class-action"><span className="live-pill">Now · 42 min left</span><button aria-label="Open Database Systems course"><PlayCircle size={18} />Open course</button></div></article><article className="schedule-class"><div className="time"><strong>11:15</strong><span>12:45 PM</span></div><div className="class-marker"><i /><span /></div><div className="class-info"><div><b>Software Engineering</b><span>CS 315 · Seminar</span></div><p><MapPin size={14} /> Engineering Hall, E-05</p></div><div className="class-action"><span className="up-next">Up next</span><button aria-label="View Software Engineering course"><ChevronRight size={18} /></button></div></article><article className="schedule-class last"><div className="time"><strong>14:00</strong><span>15:30 PM</span></div><div className="class-marker"><i /></div><div className="class-info"><div><b>Discrete Mathematics</b><span>MATH 241 · Lecture</span></div><p><MapPin size={14} /> Lecture Theatre 4</p></div></article></div></section>
    <div className="dashboard-columns"><section className="courses-section"><div className="section-heading"><div><p className="eyebrow">This semester</p><h2>Active courses</h2></div><Link href="/dashboard/student/results">View all <ArrowRight size={16} /></Link></div><div className="course-grid">{resultCourses.map((course) => <article className="course-card" key={course.code}><div className={`course-art ${course.tone}`}><BookOpen size={23} /><span>{course.code}</span></div><div className="course-content"><div><span className="course-code">{course.code}</span><h3>{course.title}</h3><p>{course.professor}</p></div><div className="course-metrics"><span><b>{course.grade}%</b> overall grade</span><span>{course.progress}% complete</span></div><div className="progress"><i style={{ width: `${course.progress}%` }} /></div></div></article>)}</div></section><aside className="tasks-section"><div className="section-heading"><div><p className="eyebrow">Stay on track</p><h2>Upcoming</h2></div><button aria-label="Add a task"><Plus size={19} /></button></div><div className="task-list"><article><span className="task-icon indigo"><FileText size={17} /></span><div><span className="task-tag">Assignment</span><h3>Database schema design</h3><p>Database Systems · <strong>Due in 3 hours</strong></p></div></article><article><span className="task-icon amber"><GraduationCap size={17} /></span><div><span className="task-tag">Quiz</span><h3>Week 5 knowledge check</h3><p>Discrete Mathematics · <strong>Tomorrow</strong></p></div></article><article><span className="task-icon rose"><ReceiptText size={17} /></span><div><span className="task-tag">Tuition</span><h3>Semester fee balance</h3><p>Finance Office · <strong>Due Oct 10</strong></p></div></article><article><span className="task-icon emerald"><FileText size={17} /></span><div><span className="task-tag">Form due</span><h3>Internship preference form</h3><p>Career Services · <strong>Due Oct 15</strong></p></div></article></div><Link className="all-tasks" href="/dashboard/student/support">View all tasks <ArrowRight size={16} /></Link></aside></div>
    <section className="stats-strip"><article><Clock3 size={20} /><div><span>Attendance average</span><b>{overview?.attendance?.length ? `${Math.round(overview.attendance.reduce((sum, item) => sum + Number(item.percentage || 0), 0) / overview.attendance.length)}%` : "92%"}</b></div></article><article><GraduationCap size={20} /><div><span>Current CGPA</span><b>{profile?.cgpa ?? "3.72"}</b></div></article><article><CircleDollarSign size={20} /><div><span>Outstanding balance</span><b>{profile?.feeBalance ? `GH₵ ${profile.feeBalance.toLocaleString()}` : "GH₵ 1,240"}</b></div><Link href="/dashboard/student/fees" aria-label="View fees"><ArrowRight size={17} /></Link></article></section>
    {loading && <div className="data-refresh" aria-live="polite">Refreshing your academic data…</div>}
  </div>;
}
