"use client";

import { useEffect, useState } from 'react';

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000/api';
type Profile = { fullName?: string; email?: string; studentId?: string; programme?: string; department?: string; level?: string; hallResidence?: string; cgpa?: number; creditsCompleted?: number; feeBalance?: number; status?: string };

export default function StudentProfilePage() {
  const [profile, setProfile] = useState<Profile>({});
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { fetch(`${API_BASE}/v1/students/me`, { credentials: 'include', headers: { Authorization: `Bearer ${localStorage.getItem('portal_token') || ''}` } }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.message); setProfile(data.profile || {}); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Unable to load profile')); }, []);
  function update(key: keyof Profile, value: string) { setProfile((current) => ({ ...current, [key]: value })); }
  async function save(event: React.FormEvent) { event.preventDefault(); setError(''); setMessage(''); const response = await fetch(`${API_BASE}/v1/students/me`, { method: 'PUT', credentials: 'include', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('portal_token') || ''}` }, body: JSON.stringify(profile) }); const data = await response.json(); if (!response.ok) { setError(data.message || 'Unable to update profile'); return; } setProfile(data.profile || profile); setMessage('Profile updated successfully.'); }
  const fields: Array<[keyof Profile, string]> = [['fullName', 'Full name'], ['programme', 'Programme'], ['department', 'Department'], ['level', 'Level'], ['hallResidence', 'Hall residence']];
  return <div className="rounded-[28px] bg-[#f8fafc] p-6 ring-1 ring-slate-200"><p className="muted-kicker">Student record</p><h2 className="mt-2 text-2xl font-bold text-[#11222d]">My profile</h2><div className="mt-4 grid gap-3 text-sm text-slate-600 sm:grid-cols-3"><div><span className="block text-xs uppercase">Student ID</span><strong>{profile.studentId || '-'}</strong></div><div><span className="block text-xs uppercase">Email</span><strong>{profile.email || '-'}</strong></div><div><span className="block text-xs uppercase">Status</span><strong className="capitalize">{profile.status || '-'}</strong></div></div><form onSubmit={save} className="mt-6 grid gap-4 sm:grid-cols-2">{fields.map(([key, label]) => <label key={key} className="text-sm font-semibold text-slate-700">{label}<input value={String(profile[key] || '')} onChange={(event) => update(key, event.target.value)} className="input-field mt-2" /></label>)}<div className="sm:col-span-2 flex items-center gap-3"><button className="rounded-lg bg-[#0d5a4d] px-4 py-2 text-sm font-semibold text-white">Save profile</button>{message && <span className="text-sm text-green-700">{message}</span>}{error && <span className="text-sm text-red-700">{error}</span>}</div></form><div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-white p-4 ring-1 ring-slate-200"><span className="text-xs text-slate-500">CGPA</span><strong className="mt-1 block text-xl">{profile.cgpa ?? '-'}</strong></div><div className="rounded-xl bg-white p-4 ring-1 ring-slate-200"><span className="text-xs text-slate-500">Credits completed</span><strong className="mt-1 block text-xl">{profile.creditsCompleted ?? '-'}</strong></div><div className="rounded-xl bg-white p-4 ring-1 ring-slate-200"><span className="text-xs text-slate-500">Fee balance</span><strong className="mt-1 block text-xl">GHS {profile.feeBalance ?? 0}</strong></div></div></div>;
}
